2024-04-10 16:12:01,478 INFO    StreamThr :5760 [internal.py:wandb_internal():86] W&B internal server running at pid: 5760, started at: 2024-04-10 16:12:01.477789
2024-04-10 16:12:01,479 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status
2024-04-10 16:12:01,485 INFO    WriterThread:5760 [datastore.py:open_for_write():85] open: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\run-hwykc84h.wandb
2024-04-10 16:12:01,486 DEBUG   SenderThread:5760 [sender.py:send():382] send: header
2024-04-10 16:12:01,527 DEBUG   SenderThread:5760 [sender.py:send():382] send: run
2024-04-10 16:12:02,126 INFO    SenderThread:5760 [dir_watcher.py:__init__():211] watching files in: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\files
2024-04-10 16:12:02,128 INFO    SenderThread:5760 [sender.py:_start_run_threads():1136] run started: hwykc84h with start time 1712758321.479288
2024-04-10 16:12:02,132 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: check_version
2024-04-10 16:12:02,132 DEBUG   SenderThread:5760 [sender.py:send_request():409] send_request: check_version
2024-04-10 16:12:02,419 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: run_start
2024-04-10 16:12:02,442 DEBUG   HandlerThread:5760 [system_info.py:__init__():32] System info init
2024-04-10 16:12:02,442 DEBUG   HandlerThread:5760 [system_info.py:__init__():47] System info init done
2024-04-10 16:12:02,442 INFO    HandlerThread:5760 [system_monitor.py:start():194] Starting system monitor
2024-04-10 16:12:02,442 INFO    SystemMonitor:5760 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-10 16:12:02,442 INFO    HandlerThread:5760 [system_monitor.py:probe():214] Collecting system info
2024-04-10 16:12:02,444 INFO    SystemMonitor:5760 [interfaces.py:start():190] Started cpu monitoring
2024-04-10 16:12:02,444 INFO    SystemMonitor:5760 [interfaces.py:start():190] Started disk monitoring
2024-04-10 16:12:02,445 INFO    SystemMonitor:5760 [interfaces.py:start():190] Started gpu monitoring
2024-04-10 16:12:02,447 INFO    SystemMonitor:5760 [interfaces.py:start():190] Started memory monitoring
2024-04-10 16:12:02,455 INFO    SystemMonitor:5760 [interfaces.py:start():190] Started network monitoring
2024-04-10 16:12:02,457 DEBUG   HandlerThread:5760 [system_info.py:probe():196] Probing system
2024-04-10 16:12:02,458 DEBUG   HandlerThread:5760 [system_info.py:_probe_git():181] Probing git
2024-04-10 16:12:02,516 DEBUG   HandlerThread:5760 [system_info.py:_probe_git():189] Probing git done
2024-04-10 16:12:02,516 DEBUG   HandlerThread:5760 [system_info.py:probe():244] Probing system done
2024-04-10 16:12:02,516 DEBUG   HandlerThread:5760 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.11.5', 'heartbeatAt': '2024-04-10T14:12:02.457213', 'startedAt': '2024-04-10T14:12:01.469486', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/Mateo-drr/Cryp-Tor.git', 'commit': '1adc8a5e4fcd3bc7f89e7c68db87e7811b9fb492'}, 'email': 'mateodrr@gmail.com', 'root': 'S:/Cryp-Tor', 'host': 'DESKTOP-24KBHOO', 'username': 'Mateo-drr', 'executable': 'C:\\Users\\Mateo-drr\\AppData\\Local\\miniconda3\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3300.0, 'min': 0.0, 'max': 3300.0}, 'cpu_freq_per_core': [{'current': 3300.0, 'min': 0.0, 'max': 3300.0}], 'disk': {'/': {'total': 465.75976181030273, 'used': 22.3953857421875}}, 'gpu': 'NVIDIA GeForce RTX 2060', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2060', 'memory_total': 12884901888}], 'memory': {'total': 15.828716278076172}}
2024-04-10 16:12:02,516 INFO    HandlerThread:5760 [system_monitor.py:probe():224] Finished collecting system info
2024-04-10 16:12:02,516 INFO    HandlerThread:5760 [system_monitor.py:probe():227] Publishing system info
2024-04-10 16:12:02,516 DEBUG   HandlerThread:5760 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-04-10 16:12:02,517 DEBUG   HandlerThread:5760 [system_info.py:_save_pip():68] Saving pip packages done
2024-04-10 16:12:02,517 DEBUG   HandlerThread:5760 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-04-10 16:12:03,131 INFO    Thread-16 :5760 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\files\requirements.txt
2024-04-10 16:12:03,131 INFO    Thread-16 :5760 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\files\conda-environment.yaml
2024-04-10 16:12:07,077 DEBUG   HandlerThread:5760 [system_info.py:_save_conda():87] Saving conda packages done
2024-04-10 16:12:07,078 INFO    HandlerThread:5760 [system_monitor.py:probe():229] Finished publishing system info
2024-04-10 16:12:07,081 DEBUG   SenderThread:5760 [sender.py:send():382] send: files
2024-04-10 16:12:07,082 INFO    SenderThread:5760 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-04-10 16:12:07,082 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:07,089 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: stop_status
2024-04-10 16:12:07,089 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:12:07,090 DEBUG   SenderThread:5760 [sender.py:send_request():409] send_request: stop_status
2024-04-10 16:12:07,148 INFO    Thread-16 :5760 [dir_watcher.py:_on_file_modified():288] file/dir modified: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\files\conda-environment.yaml
2024-04-10 16:12:07,149 INFO    Thread-16 :5760 [dir_watcher.py:_on_file_created():271] file/dir created: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\files\wandb-metadata.json
2024-04-10 16:12:07,511 DEBUG   SenderThread:5760 [sender.py:send():382] send: telemetry
2024-04-10 16:12:07,873 INFO    wandb-upload_0:5760 [upload_job.py:push():131] Uploaded file C:\Users\MATEO-~1\AppData\Local\Temp\tmpmjwg0j46wandb\jmunrctj-wandb-metadata.json
2024-04-10 16:12:12,542 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:17,575 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:22,080 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: stop_status
2024-04-10 16:12:22,080 DEBUG   SenderThread:5760 [sender.py:send_request():409] send_request: stop_status
2024-04-10 16:12:22,094 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:12:23,324 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:28,364 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:33,422 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: status_report
2024-04-10 16:12:33,577 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:12:33,577 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:12:34,873 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:12:34,873 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:12:37,038 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:12:37,038 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:12:37,038 INFO    SenderThread:5760 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-04-10 16:12:37,105 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: stop_status
2024-04-10 16:12:37,105 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:12:41,946 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:12:41,946 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:12:42,132 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:12:47,162 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:12:52,112 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:12:52,112 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:12:52,113 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:12:57,244 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:02,260 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:02,461 DEBUG   SystemMonitor:5760 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-10 16:13:07,126 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:13:08,519 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:13:08,519 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:13:12,303 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:17,358 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:22,130 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:13:27,469 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:32,521 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:37,139 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:13:42,642 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:43,541 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:13:43,541 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:13:47,701 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:13:52,154 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:13:57,810 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:02,872 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:07,166 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:14:12,965 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:18,027 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:22,167 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:14:28,147 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:33,208 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:37,177 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:14:42,299 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:47,330 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: keepalive
2024-04-10 16:14:51,923 ERROR   SenderThread:5760 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-04-10 16:14:51,923 ERROR   SenderThread:5760 [internal_api.py:execute():374] {"errors":[{"message":"run hwykc84h was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-10 16:14:52,180 DEBUG   HandlerThread:5760 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-10 16:14:52,180 INFO    HandlerThread:5760 [handler.py:finish():866] shutting down handler
2024-04-10 16:14:52,180 INFO    HandlerThread:5760 [system_monitor.py:finish():203] Stopping system monitor
2024-04-10 16:14:52,181 DEBUG   SystemMonitor:5760 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-10 16:14:52,184 DEBUG   SystemMonitor:5760 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-10 16:14:52,184 INFO    HandlerThread:5760 [interfaces.py:finish():202] Joined cpu monitor
2024-04-10 16:14:52,184 INFO    HandlerThread:5760 [interfaces.py:finish():202] Joined disk monitor
2024-04-10 16:14:52,206 INFO    HandlerThread:5760 [interfaces.py:finish():202] Joined gpu monitor
2024-04-10 16:14:52,206 INFO    HandlerThread:5760 [interfaces.py:finish():202] Joined memory monitor
2024-04-10 16:14:52,206 INFO    HandlerThread:5760 [interfaces.py:finish():202] Joined network monitor
2024-04-10 16:14:52,643 INFO    WriterThread:5760 [datastore.py:close():294] close: S:\Cryp-Tor\wandb\run-20240410_161201-hwykc84h\run-hwykc84h.wandb
2024-04-10 16:14:52,643 ERROR   StreamThr :5760 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2212, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal_util.py", line 93, in _run
    self._debounce()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\internal.py", line 334, in _debounce
    self._sm.debounce()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\sender.py", line 540, in debounce
    self._maybe_update_config(always=final)
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\sender.py", line 517, in _maybe_update_config
    self._debounce_config()
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\sdk\internal\sender.py", line 546, in _debounce_config
    self._api.upsert_run(
  File "C:\Users\Mateo-drr\AppData\Local\miniconda3\Lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run hwykc84h was previously created and deleted; try a new run name (Error 409: Conflict)
